name: Test source code

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  pretty:
    runs-on: ubuntu-latest

    steps:
      - name: Instasll dependancies
        run: npm install --save-dev --seve-extract 'prettier@3.3.3'

      - name: Check if all is pretty
        run: npx prettier . --check
