name: Test source code

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  pretty:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Instasll dependancies
        run: |
          npm install --save-dev --seve-extract 'prettier@3.3.3'
          pip install black==24.8.0

      - name: Check if all is pretty
        run: npx prettier . --check

      - name: Check if py is black
        run: python3 -m black --check main.py lib
